plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

# Estilo pragmático para no pelear con el scaffold
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "spec/**/*"
    - "db/**"

Layout/LineLength:
  Max: 120
  Exclude:
    - "config/**/*"